version: '3'

services:
  cbp-server:
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    container_name: "portal_server"
    restart: always
    environment: 
      - APP_NAME=PORTAL
    expose:
      - "3000"
    volumes:
      - ./server:/server
      - ./tmp:/tmp
    env_file: 
      - .env

  nginx:
    build: ./client
    container_name: "portal_nginx"
    restart: always
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules
      - ./tmp:/tmp
    ports:
        - "89:80"
    environment:
        - API_HOST=portal_server
        - API_PORT=3000
        
  cbp-db:
    image: mongo:latest
    container_name: "portal_mongo"
    command: mongod --port 27013
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: flask_db
      MONGODB_DATA_DIR: /var/lib/mongodb-data
      MONDODB_LOG_DIR: /dev/null
    volumes:
     - mongodb-data:/var/lib/mongodb-data
    ports:
      - "27013:27013"

volumes:
  app:
  mongodb-data:
  node_modules:
