version: '3'

services:
  cbp-server:
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    container_name: 'cbp_server'
    restart: always
    environment: 
      - APP_NAME=CBP
    expose:
      - "8383"
    volumes:
      - ./server:/server
      - ./tmp:/tmp
    env_file: 
      - .env

  nginx:
    build: ./client
    container_name:  cbp_nginx
    restart: always
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules
      - ./tmp:/tmp
    ports:
        - "85:85"
    environment:
        - API_HOST=cbp-server
        - API_PORT=8383
        
  cbp-db:
    image: mongo:latest
    container_name: "cbp_mongo"
    command: mongod --port 27010
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: flask_db
      MONGODB_DATA_DIR: /var/lib/mongodb-data
      MONDODB_LOG_DIR: /dev/null
    volumes:
     - mongodb-data:/var/lib/mongodb-data
    ports:
      - "27010:27010"

volumes:
  app:
  mongodb-data:
  node_modules:
