
name: ci

on:
  push:
    branches:
      - 'main'
      
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./client/Dockerfile
            label: biogenome-front
            path: /client
            image: client
            version: latest
          - dockerfile: ./server/Dockerfile
            label: biogenome-back
            image: server
            version: latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{matrix.label}}
          heroku_email: ${{secrets.USER_EMAIL}}
          appdir: ${{matrix.image}}
          usedocker: true
